name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: 19
          distribution: oracle
      - name: build cache
        run: ./gradlew typeParser
      - name: build server
        run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: data
          path: data
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs/game-server.jar
          if-no-files-found: error